#!/bin/sh

# Wait until waybar is fully available (for tray)
wait_waybar () {
    # Ask dbus to check if waybar is available
    while [[ -z $(dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep "fr.arouillard.waybar" ) ]]
    do 
        sleep 0.5
    done
}

# Per computer processus
if command -v gammastep > /dev/null 2>&1; then
    gammastep& # Blue light reducer
fi
if command -v kanata > /dev/null 2>&1; then
    kanata& # Multi layer keyboard on a classical one
fi
bluetoothctl power off # power off bluetooth at startup

# Start other processus
wait_waybar
if command -v keepassxc > /dev/null 2>&1; then
    keepassxc&
fi
