#!/bin/sh

# Start a processus only if it isn't already running
# start_once () {
#     process=$(pidof $1); # Check if the processus is already started
#     if [[ -z $process ]];
#     then
#         $1& # Start the processus
#     fi
# }

# Start other processus
pipewire&
pipewire-pulse&
wireplumber&
keepassxc&

# Per computer processus
gammastep& # Blue light reducer
rfkill unblock bluetooth # Unblock soft-bluetooth
bluetoothctl power off # power off bluetooth at startup