#!/bin/sh

# Start other processus
pipewire&
pipewire-pulse&
wireplumber&
asus-numpad& # asus numpad in touchpad
rclone mount googleDrive:/ ~/googleDrive& # Google drive
#rfkill unblock bluetooth # Unblock soft-bluetooth
keepassxc&