theme = "monokai_custom"

[editor]
auto-save.focus-lost = true # default: false
auto-save.after-delay.enable = true # default: false
auto-save.after-delay.timeout = 500 # range: [0; u64::MAX] default: 3000
color-modes = true
bufferline = "multiple"
preview-completion-insert = false
completion-replace = true
continue-comments = true
line-number = "relative"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "diagnostics"]
center = ["file-name"]
right = ["position", "total-line-numbers", "separator", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
"S-A-e" = ":fmt"
"C-h" = "toggle_comments"
"C-d" = ["search_selection", "select_mode", "extend_search_next", "normal_mode"]
"tab" = "indent"
"S-tab" = "unindent"
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# custom movements and key swaps
"n" = "move_char_right"
"t" = "move_char_left"
"r" = "move_visual_line_down"
"s" = "move_visual_line_up"
"C-s" = "page_cursor_half_up"
"C-r" = "page_cursor_half_down"

"l" = "open_below"
"L" = "open_above"

"o" = "replace"
"j" = "select_regex"
"'" = "search_next"
"?" = "search_prev"

[keys.select]
"S-A-e" = ":fmt"
"C-h" = "toggle_comments"
"C-d" = ["search_selection", "select_mode", "extend_search_next", "normal_mode"]
"tab" = "indent"
"S-tab" = "unindent"
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# custom movements and key swaps
"n" = "extend_char_right"
"t" = "extend_char_left"
"r" = "extend_visual_line_down"
"s" = "extend_visual_line_up"
"C-s" = "page_cursor_half_up"
"C-r" = "page_cursor_half_down"

"l" = "open_below"
"L" = "open_above"

"o" = "replace"
"j" = "select_regex"
"'" = "search_next"
"?" = "search_prev"

[keys.insert]
"S-A-e" = ":fmt"
"C-h" = "toggle_comments"
"C-d" = ["search_selection", "select_mode", "extend_search_next", "insert_mode"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]

"A-s" = "normal_mode"

"C-space" =  "completion"

[keys.normal.g]
"s" = "move_line_up"
"r" = "move_line_down"

[keys.select.g]
"s" = "move_line_up"
"r" = "move_line_down"

[keys.normal."é"]
"c" = "align_view_center"
"t" = "align_view_top"
"b" = "align_view_bottom"
"m" = "align_view_middle"
"s" = "scroll_up"
"r" = "scroll_down"
