theme = "monokai_custom"

[editor]
auto-save.focus-lost = true # default: false
auto-save.after-delay.enable = true # default: false
auto-save.after-delay.timeout = 500 # range: [0; u64::MAX] default: 3000
color-modes = true
bufferline = "multiple"
preview-completion-insert = false
completion-replace = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "diagnostics"]
center = ["file-name"]
right = ["position", "total-line-numbers", "separator", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
"S-A-e" = ":fmt"
"C-h" = "toggle_comments"
"C-c" = ":clipboard-yank"
"C-x" = [":clipboard-yank", "delete_selection"]
"C-v" = ":clipboard-paste-replace"

# custom movements and key swaps
"n" = "move_char_right"
"s" = "move_char_left"
"h" = "move_visual_line_down"
"l" = "move_visual_line_up"

"j" = "select_regex"
"C-i" = "page_cursor_half_down"

"C-d" = ["search_selection", "select_mode", "extend_search_next", "normal_mode"]
"tab" = "indent"
"S-tab" = "unindent"
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

"C-q" = ":quit"

[keys.select]
"S-A-e" = ":fmt"
"C-h" = "toggle_comments"
"C-c" = ":clipboard-yank"
"C-x" = [":clipboard-yank", "delete_selection"]
"C-v" = ":clipboard-paste-replace"

# custom movements and key swaps
"n" = "extend_char_right"
"s" = "extend_char_left"
"h" = "extend_visual_line_down"
"l" = "extend_visual_line_up"

"j" = "select_regex"
"k" = "extend_search_next"
"K" = "extend_search_prev"

"tab" = "indent"
"S-tab" = "unindent"

[keys.insert]
"S-A-e" = ":fmt"
"C-h" = "toggle_comments"
"C-c" = ":clipboard-yank"
"C-x" = [":clipboard-yank", "delete_selection"]
"C-v" = ":clipboard-paste-replace"

"C-space" =  "completion"

A-down = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]

